services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - playwise

  postgres:
    container_name: playwise-postgres
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_USER: "HarshPatel"
      POSTGRES_PASSWORD: "Password"
      POSTGRES_DB: "playwise"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - playwise

volumes:
  postgres_data:
networks:
  playwise:
